#DataBase properties
spring:
 user:
  datasource:
   jdbcUrl : jdbc:mysql://localhost:3306/datasource3
   username : root
   password: root
   driver-class-name : com.mysql.cj.jdbc.Driver
 book:
  datasource:
   jdbcUrl : jdbc:mysql://localhost:3306/datasource3
   username : root
   password: root
   driver-class-name : com.mysql.cj.jdbc.Driver
 jpa:
  generate-ddl : true
 jpa.show-sql : true   
 autoconfigure:
 #exclude : org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

